org: ldrogan
app: aws-serverless-sns
service: aws-serverless-sns

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
